---
- name: Uninstall golang from source
  block:
    - name: Find existing golang folder in {{ golang_install_dir }}
      ansible.builtin.find:
        paths: "{{ golang_install_dir }}"
        patterns: "go-*"
        file_type: directory
      register: golang_install_folder

    - name: Remove existing golang installation folder
      ansible.builtin.file:
        path: "{{ folder.path }}"
        state: absent
      loop: "{{ golang_install_folder.files }}"
      loop_control:
        loop_var: folder
      become: true

    - name: Remove golang symlink
      ansible.builtin.file:
        path: "/usr/local/bin/go"
        state: absent
      become: true
