---
- name: Converge
  hosts: all

  vars:
    ansible_user: "root"
    golang_tools:
      - name: "github.com/tomnomnom/gf"
        version: "dcd4c361f9f5ba302294ed38b8ce278e8ba69006"

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: pluggero.golang
